# The URL the site will be built for
base_url = "https://heymisphere.github.io"
title = "Hemish"
compile_sass = false
default_language = "en"
feed_filename = "rss.xml"
build_search_index = true
taxonomies = [
    {name = "tags", feed = true, paginate_by = 5},
    {name = "languages", feed = true, paginate_by = 5}
]

[markdown]
highlight_code = true
highlight_theme = "base16-ocean-dark"
external_links_target_blank = true

[extra]
# Put all your custom variables here
